#!/usr/bin/bash

CONFIG=gid-vpn-plalexeev-3.ovpn

#CHECK_URL='https://jira.gid.team/s/d41d8cd98f00b204e9800998ecf8427e-CDN/4vmsmm/9120001/4m6das/7.5.0/_/download/resources/com.atlassian.jira.plugins.jira-editor-plugin:tinymce/tinymce-amd.js'
#CHECK_PING_HOST=jira.gid.team
CHECK_URL='https://gitlab.gid.team/assets/webpack/pages.root.e23b2a19.chunk.js'
CHECK_PING_HOST=gitlab.gid.team
